# Generated by Django 5.1.7 on 2025-03-19 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('contact_person', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('pf_no', models.BigIntegerField()),
                ('pf_group_code', models.BigIntegerField()),
                ('pf_office', models.TextField()),
                ('esic_no', models.BigIntegerField()),
                ('esic_group_code', models.BigIntegerField()),
                ('esic_office', models.TextField()),
                ('company_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Master.company')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('principle_employer', models.CharField(max_length=50)),
                ('contractor_name', models.CharField(max_length=50)),
                ('contractor_address', models.TextField()),
                ('sub_contractor_name', models.CharField(max_length=50)),
                ('sub_contractor_address', models.TextField()),
                ('main_contractor_name', models.CharField(max_length=50)),
                ('main_contractor_address', models.TextField()),
                ('esic_no', models.BigIntegerField()),
                ('esic_group_code', models.BigIntegerField()),
                ('esic_office', models.TextField()),
                ('branch_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Master.branch')),
                ('company_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Master.company')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.TextField()),
                ('name', models.CharField(max_length=50)),
                ('father_husband_name', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=50)),
                ('regular', models.BooleanField(default=True)),
                ('salary_type', models.CharField(max_length=50)),
                ('epf', models.BooleanField(default=True)),
                ('pension', models.BooleanField(default=True)),
                ('edli', models.BooleanField()),
                ('esi', models.BooleanField(default=True)),
                ('epf_non_regular', models.BooleanField(default=False)),
                ('esi_non_regular', models.BooleanField(default=False)),
                ('pf_limit_employee', models.IntegerField(default=6500)),
                ('pf_limit_employer', models.IntegerField(default=6500)),
                ('esi_limit_employee', models.IntegerField(default=7500)),
                ('esi_limit_employer', models.IntegerField(default=7500)),
                ('pf_number', models.TextField()),
                ('nssn', models.TextField()),
                ('esi_number', models.TextField()),
                ('dispensary', models.TextField()),
                ('reason_of_quit', models.CharField(max_length=50)),
                ('marital_status', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('date_of_left', models.DateField()),
                ('date_of_joining', models.DateField()),
                ('date_of_retire', models.DateField()),
                ('date_of_pf', models.DateField()),
                ('date_of_esic', models.DateField()),
                ('age', models.IntegerField()),
                ('inc_month', models.IntegerField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Master.branch')),
                ('company_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Master.company')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Master.department')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Master.designation')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('company_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Master.company')),
            ],
        ),
    ]
